image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      sudo sed -i '1s/^/export LANGUAGE=en_US \n/' /opt/google/chrome/google-chrome
      npm install -g npm
      npm install -g npm@9.2.0
      npm install
      sed -i "s/<your workspace id>/$workspaceid/g" test/helper/jest.setup.ts
      sed -i "s/<your access token>/$accesstoken/g" test/helper/jest.setup.ts
    command: |
      gp open test/my-first-askui-test-suite.test.ts
      gp open README.md
      echo '**********************************'
      echo '** Start first askui automation **'
      echo '**********************************'
      npm run askui-automation
  
      
ports:
  - port: 6080
    onOpen: open-preview
