image:
  file: .gitpod.Dockerfile

tasks:
  - name: Open readme
    command: gp await port 23000 1>/dev/null && gp open README.md
  - init: |
      npm install -g npm
      npm install
      sed -i "s/<your workspace id>/$workspaceid/g" test/helper/jest.setup.ts
      sed -i "s/<your access token>/$accesstoken/g" test/helper/jest.setup.ts
    command: |
      gp open test/my-first-askui-test-suite.test.ts
      gp open README.md
      echo '**********************************'
      echo '** Start first askui automation **'
      echo '**********************************'
      npm run askui-automation
  
      
ports:
  - port: 6080
    onOpen: open-preview
