image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      npm install -g npm@10.2.3
      nvm install --lts
      nvm use --lts
      npm install
      sed -i "s/<your workspace id>/$workspaceid/g" askui_example/helpers/askui-helper.ts
      sed -i "s/<your access token>/$accesstoken/g" askui_example/helpers/askui-helper.ts
    command: |
      gp open askui_example/my-first-askui-test-suite.test.ts
      gp open README.md
      echo '**********************************'
      echo '** Start first AskUI automation **'
      echo '**********************************'
      npm run askui
  
      
ports:
  - port: 6080
    onOpen: open-preview
