image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      npm install -g npm
      npm install
      echo 'Start first askui automation'
      npm run askui-automation
      
ports:
  - port: 6080
    onOpen: open-preview
